### ISSUE TITLE
Closing welcome panel causes crash

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/SciQLop#32]
* SciQLop version: c356ca3
* Python version:3.10
* Operating System:Mac OS 13.3 (ventura) and above

### Description

Closing the welcome panel and adding a new plot panel leads to the app crashing.

**Comment by jeandet** [comment]
I suspect this is either a [QtADS](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System) bug, I hope next release will fix it.
