### ISSUE TITLE
plot list in inspector not synchronized with plot actually displayed 

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/SciQLop#36]
* SciQLop version: c356ca3d
* Python version: 3.10
* Operating System: Mac OS 13.3

### Description

Number of plots in inspector not updated after adding one plot in the panel
6 plots listed VS 7 plots displayed 

<img width="1492" alt="image" src="https://github.com/SciQLop/SciQLop/assets/3200931/1081e391-d345-4323-bea6-d75def67a855">

the number of plots listed appeared updated once I closed and re-opened the inspector panel.

<img width="1497" alt="image" src="https://github.com/SciQLop/SciQLop/assets/3200931/78cd3a01-d910-4ea1-aca8-4b0af49bc037">

**Comment by jeandet** [comment]
Not sure how to reproduce this one. Do you have more details?
